-- ------------------------------------------------------------
-- 1. DATABASE & TABLE EXPLORATION
-- ------------------------------------------------------------

-- View all tables available in the database
SELECT *
FROM INFORMATION_SCHEMA.TABLES;


-- View all columns and table structures
SELECT *
FROM INFORMATION_SCHEMA.COLUMNS;


-- ------------------------------------------------------------
-- 2. CUSTOMER EDA
-- ------------------------------------------------------------

-- View all countries where customers are located
SELECT DISTINCT
    country
FROM gold.customers;


-- Count customers by country
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.customers
GROUP BY country
ORDER BY total_customers DESC;


-- Analyze customer distribution by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.customers
GROUP BY gender
ORDER BY total_customers DESC;


-- Analyze customer distribution by marital status
SELECT
    marital_status,
    COUNT(customer_key) AS total_customers
FROM gold.customers
GROUP BY marital_status
ORDER BY total_customers DESC;


-- Analyze customer acquisition by year
SELECT
    YEAR(create_date) AS create_year,
    COUNT(customer_key) AS total_customers
FROM gold.customers
GROUP BY YEAR(create_date)
ORDER BY create_year;


-- Identify the oldest and youngest customer birthdates
SELECT
    MIN(birthdate) AS oldest_birthdate,
    MAX(birthdate) AS youngest_birthdate
FROM gold.customers;


-- ------------------------------------------------------------
-- 3. PRODUCT EDA
-- ------------------------------------------------------------

-- View product categories, subcategories, and product names
SELECT
    category,
    subcategory,
    product_name
FROM gold.products
ORDER BY
    category,
    subcategory;


-- Count products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.products
GROUP BY category
ORDER BY total_products DESC;


-- Count products by category and subcategory
SELECT
    category,
    subcategory,
    COUNT(product_key) AS total_products
FROM gold.products
GROUP BY
    category,
    subcategory
ORDER BY total_products DESC;


-- Calculate average product cost by category
SELECT
    category,
    AVG(cost) AS average_cost
FROM gold.products
GROUP BY category
ORDER BY average_cost DESC;


-- Identify the top 10 products with the highest cost
SELECT TOP 10
    product_name,
    category,
    subcategory,
    cost
FROM gold.products
ORDER BY cost DESC;


-- Identify the top 10 products with the lowest cost
SELECT TOP 10
    product_name,
    category,
    subcategory,
    cost
FROM gold.products
ORDER BY cost;


-- ------------------------------------------------------------
-- 4. SALES EDA
-- ------------------------------------------------------------

-- Identify the overall transaction period
SELECT
    MIN(order_date) AS first_order,
    MAX(order_date) AS last_order,
    DATEDIFF(
        YEAR,
        MIN(order_date),
        MAX(order_date)
    ) AS range_years
FROM gold.sales;


-- View all sales transactions
SELECT *
FROM gold.sales;


-- Calculate key sales metrics
SELECT
    SUM(quantity) AS total_sold,
    SUM(sales_amount) AS total_sales,
    AVG(price) AS average_price,
    COUNT(order_number) AS total_orders,
    COUNT(DISTINCT product_key) AS total_products_sold,
    COUNT(DISTINCT customer_key) AS total_customers
FROM gold.sales;


-- Analyze revenue by product category
SELECT
    p.category,
    SUM(s.sales_amount) AS revenue
FROM gold.sales AS s
LEFT JOIN gold.products AS p
    ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY revenue DESC;


-- Analyze revenue by product subcategory
SELECT
    p.category,
    p.subcategory,
    SUM(s.sales_amount) AS revenue
FROM gold.sales AS s
LEFT JOIN gold.products AS p
    ON s.product_key = p.product_key
GROUP BY
    p.category,
    p.subcategory
ORDER BY revenue DESC;


-- ------------------------------------------------------------
-- 5. CUSTOMER SALES EDA
-- ------------------------------------------------------------

-- Analyze revenue generated by each customer
SELECT
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    SUM(s.sales_amount) AS revenue
FROM gold.sales AS s
LEFT JOIN gold.customers AS c
    ON s.customer_key = c.customer_key
GROUP BY
    CONCAT(c.first_name, ' ', c.last_name)
ORDER BY revenue DESC;


-- Identify the top 10 customers by revenue
SELECT TOP 10
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    SUM(s.sales_amount) AS revenue
FROM gold.sales AS s
LEFT JOIN gold.customers AS c
    ON s.customer_key = c.customer_key
GROUP BY
    CONCAT(c.first_name, ' ', c.last_name)
ORDER BY revenue DESC;


-- Analyze revenue generated by customer country
SELECT
    c.country,
    SUM(s.sales_amount) AS revenue
FROM gold.sales AS s
LEFT JOIN gold.customers AS c
    ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY revenue DESC;


-- Compare customer count and revenue by country
SELECT
    c.country,
    COUNT(DISTINCT c.customer_key) AS total_customers,
    SUM(s.sales_amount) AS revenue
FROM gold.sales AS s
LEFT JOIN gold.customers AS c
    ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY revenue DESC;


-- ------------------------------------------------------------
-- 6. PRODUCT PERFORMANCE
-- ------------------------------------------------------------

-- Analyze revenue and quantity sold by product
SELECT
    p.product_name,
    p.category,
    p.subcategory,
    SUM(s.sales_amount) AS revenue,
    SUM(s.quantity) AS quantity_sold
FROM gold.sales AS s
LEFT JOIN gold.products AS p
    ON s.product_key = p.product_key
GROUP BY
    p.product_name,
    p.category,
    p.subcategory
ORDER BY revenue DESC;


-- Identify the top 10 products by revenue
SELECT TOP 10
    p.product_name,
    p.category,
    SUM(s.sales_amount) AS revenue
FROM gold.sales AS s
LEFT JOIN gold.products AS p
    ON s.product_key = p.product_key
GROUP BY
    p.product_name,
    p.category
ORDER BY revenue DESC;


-- Identify the top 10 products by quantity sold
SELECT TOP 10
    p.product_name,
    p.category,
    SUM(s.quantity) AS quantity_sold
FROM gold.sales AS s
LEFT JOIN gold.products AS p
    ON s.product_key = p.product_key
GROUP BY
    p.product_name,
    p.category
ORDER BY quantity_sold DESC;


-- ------------------------------------------------------------
-- 7. SALES TREND
-- ------------------------------------------------------------

-- Analyze yearly revenue trends
SELECT
    YEAR(order_date) AS order_year,
    SUM(sales_amount) AS revenue
FROM gold.sales
GROUP BY YEAR(order_date)
ORDER BY order_year;


-- Analyze monthly revenue trends
SELECT
    YEAR(order_date) AS order_year,
    MONTH(order_date) AS order_month,
    SUM(sales_amount) AS revenue
FROM gold.sales
GROUP BY
    YEAR(order_date),
    MONTH(order_date)
ORDER BY
    order_year,
    order_month;


-- Analyze the number of orders by year
SELECT
    YEAR(order_date) AS order_year,
    COUNT(DISTINCT order_number) AS total_orders
FROM gold.sales
GROUP BY YEAR(order_date)
ORDER BY order_year;


-- ------------------------------------------------------------
-- 8. SALES PERFORMANCE
-- ------------------------------------------------------------

-- Calculate Average Order Value (AOV)
SELECT
    SUM(sales_amount)
        / COUNT(DISTINCT order_number) AS average_order_value
FROM gold.sales;


-- Calculate average quantity purchased per order
SELECT
    CAST(SUM(quantity) AS DECIMAL(18,2))
        / COUNT(DISTINCT order_number) AS average_quantity_per_order
FROM gold.sales;


-- Analyze revenue by customer gender
SELECT
    c.gender,
    SUM(s.sales_amount) AS revenue
FROM gold.sales AS s
LEFT JOIN gold.customers AS c
    ON s.customer_key = c.customer_key
GROUP BY c.gender
ORDER BY revenue DESC;


-- Analyze revenue by customer marital status
SELECT
    c.marital_status,
    SUM(s.sales_amount) AS revenue
FROM gold.sales AS s
LEFT JOIN gold.customers AS c
    ON s.customer_key = c.customer_key
GROUP BY c.marital_status
ORDER BY revenue DESC;